---
title: "Tracking out of the box events"
output:
  html_document:
    toc_float: false
    includes:
      before_body: [navbar.html, navbar_left.html]

---

A number of tracking events are available out of the box. These include, but aren't limited to:

- Page views
- Heartbeats (Page Pings)
- Link clicks
- HTML form actions

In this section, we will implement all 4 of these built-in events.

***

### **Step 1:** Enable Activity Tracking
First we will enable activity tracking to collect 'page ping' events. This will allow us to monitor engagement and record how a user digests content on the page over time. 

  - `minimumVisitLength` : The number of seconds from page load before the first page ping occurs
  - `heartbeatDelay`: The number of seconds between page pings 

Add the snippet to your `script` tag below the tracker instance. 

```javascript
snowplow('enableActivityTracking', { 
  minimumVisitLength: 5, 
  heartbeatDelay: 10 
});
```

**Should we encourage call back function to limit number of events sent with enableActivityTrackingCallback?**

***

### **Step 2:** Track Page View
To track a page view, simply call `trackPageView'. 

```javascript
snowplow('trackPageView')
```
**Note:** `trackPageView` should go after the page ping event in step 1

***

### **Step 3:**  Link Click Tracking
To enable link click tracking, call the `enableLinkClickTracking` method.

```javascript
snowplow('enableLinkClickTracking');
```

You only need to call the method once to track all the links on a page. This will capture the links `href` by default as well as the `id`, `class` and `target` of the link.
  
**Add more complex link tracking?**

***

### **Step 4:** HTML Form Tracking
To enable form tracking, simply call the `enableFormTracking` method.

```javascript
snowplow('enableFormTracking');
```

This will track an event when a user focuses, changes or submits a form.

### [NEXT -> Tracking Design](tracking_3.html)
