---
title: "Install and Initialise the JS tracker"
output:
  html_document:
    toc_float: false
    includes:
      before_body: [includes/navbar.html, includes/navbar_left.html]

---

Getting started with sending events using the JavaScript tracker is very similar to other web analytics vendors like Google Analytics and Adobe Analytics. 

Once setup, you will have the ability to send behavioral data to your Snowplow pipeline.

***

### **Step 1:** Download sp.js
Add the sp.js file to your project directory. The latest version can be found [here](https://github.com/snowplow/snowplow-javascript-tracker/releases). 

*** 

### **Step 2:** Add JS snippet
Add the below snippet to all of the pages you would like to track. **Make sure to update the link to the sp.js file**

Typically this will be placed into the `<head>` element of your page or in a similar, suitable, location if using a Single Page Application framework.

```javascript
<script type="text/javascript" async=1 >
;(function (p, l, o, w, i, n, g) { if (!p[i]) { p.GlobalSnowplowNamespace = p.GlobalSnowplowNamespace || []; p.GlobalSnowplowNamespace.push(i); p[i] = function () { (p[i].q = p[i].q || []).push(arguments) }; p[i].q = p[i].q || []; n = l.createElement(o); g = l.getElementsByTagName(o)[0]; n.async = 1; n.src = w; g.parentNode.insertBefore(n, g) } }(window, document, "script", "{{Link to sp.js file}}", "snowplow"));
<script>
```

***

### **Step 3:** Configure your Tracker
Call `newTracker` with the following arguments. This creates an instance of a basic tracker without any additional contexts.

- Tracker Name: `'sp'`
- Collector Url: `'{{Url for Collector}}'`

```javascript 
window.snowplow('newTracker', 'sp', '{{Url for Collector}}')
```

**point the collector to mini/micro collector for testing**

In addition to the basic tracker, add the below optional arguments to the tracker to make use of some of Snowplow's more advanced features.

- Optional Settings (JSON):
  - `appId`: Identify events that occur on different applications
  - `platform`: Identify the platform the event occurred on, in this case `web`
  - `cookieSameSite`: Lax **Not sure why, or what explanation to give, but is recomended**

```javascript 
window.snowplow('newTracker', 'sp', '{{Url for Collector}}', { 
    appId: 'appId',
    platform: 'web',
    cookieSameSite: 'Lax',
});
```

***

Now you have a tracker set up, you can begin to implement event tracking in your web app.

### [NEXT -> Tracking out of the box events](tracking_2.html)

<!-- 
## Quarterly Results {.tabset .tabset-fade}

### Tab Example  

### Tab Example 2 -->